name: employee_manager
description: "An app to manage your employees."
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  go_router: ^14.7.2
  sqflite: ^2.4.1
  floor: ^1.5.0
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  bloc_test: ^10.0.0
  freezed: ^3.0.0-0.0.dev
  floor_generator: ^1.5.0
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
